// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using zad3.Database;

#nullable disable

namespace zad3.Migrations
{
    [DbContext(typeof(BooksDbContext))]
    [Migration("20231101115245_dataSeeding")]
    partial class dataSeeding
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("zad3.Models.Book", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<double>("Rating")
                        .HasColumnType("float");

                    b.Property<string>("Synopsis")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Title")
                        .IsUnique();

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b5c1957c-4e2f-4fa6-86bb-4f1affb307de"),
                            Author = "J.K. Rowling",
                            Rating = 4.5,
                            Synopsis = "Harry Potter is a series of seven fantasy novels written by British author J. K. Rowling.",
                            Title = "Harry Potter"
                        },
                        new
                        {
                            Id = new Guid("1e98c12e-7270-4396-bca4-96b79e9ecb49"),
                            Author = "J.R.R. Tolkien",
                            Rating = 5.0,
                            Synopsis = "The Lord of the Rings is an epic fantasy novel written by English author J. R. R. Tolkien.",
                            Title = "The Lord of the Rings"
                        },
                        new
                        {
                            Id = new Guid("55418966-489d-43f8-acb0-16d387e5da1e"),
                            Author = "J.R.R. Tolkien",
                            Rating = 5.0,
                            Synopsis = "The Hobbit, or There and Back Again is a children's fantasy novel by English author J. R. R. Tolkien.",
                            Title = "The Hobbit"
                        },
                        new
                        {
                            Id = new Guid("8b114d65-5742-4d71-858e-35f57ef34d86"),
                            Author = "Dan Brown",
                            Rating = 3.8999999999999999,
                            Synopsis = "The Da Vinci Code is a 2003 mystery thriller novel by Dan Brown. It is Brown's second novel to include the character Robert Langdon: the first was his 2000 novel Angels & Demons.",
                            Title = "The Da Vinci Code"
                        },
                        new
                        {
                            Id = new Guid("e6937dc0-b98f-4114-8d3b-48be886b72c4"),
                            Author = "Dan Brown",
                            Rating = 4.7000000000000002,
                            Synopsis = "Angels & Demons is a 2000 bestselling mystery-thriller novel written by American author Dan Brown and published by Pocket Books and then by Corgi Books.",
                            Title = "Angels & Demons"
                        },
                        new
                        {
                            Id = new Guid("d059416a-54e7-41b8-9bcf-15386abf5796"),
                            Author = "Dan Brown",
                            Rating = 4.0999999999999996,
                            Synopsis = "The Lost Symbol is a 2009 novel written by American writer Dan Brown. It is a thriller set in Washington, D.C., after the events of The Da Vinci Code, and relies on Freemasonry for both its recurring theme and its major characters.",
                            Title = "The Lost Symbol"
                        },
                        new
                        {
                            Id = new Guid("b68dcf1a-2ca6-4558-920a-e265bd83cd88"),
                            Author = "Suzanne Collins",
                            Rating = 4.9000000000000004,
                            Synopsis = "The Hunger Games is a 2008 dystopian novel by the American writer Suzanne Collins. It is written in the voice of 16-year-old Katniss Everdeen, who lives in the future, post-apocalyptic nation of Panem in North America.",
                            Title = "The Hunger Games"
                        },
                        new
                        {
                            Id = new Guid("552ede80-1162-4c2b-9099-9fa3ca872e2c"),
                            Author = "Suzanne Collins",
                            Rating = 2.5,
                            Synopsis = "Catching Fire is a 2009 science fiction young adult novel by the American novelist Suzanne Collins, the second book in The Hunger Games series.",
                            Title = "Catching Fire"
                        },
                        new
                        {
                            Id = new Guid("e8d8c843-d7cb-4e2f-9e04-ab97aa1cc442"),
                            Author = "Suzanne Collins",
                            Rating = 4.7000000000000002,
                            Synopsis = "Mockingjay is a 2010 science fiction novel by American author Suzanne Collins. It is the last installment of The Hunger Games, following 2008's The Hunger Games and 2009's Catching Fire.",
                            Title = "Mockingjay"
                        },
                        new
                        {
                            Id = new Guid("6ef8a11b-8252-4062-b37e-8282d4a951e1"),
                            Author = "Andy Weir",
                            Rating = 3.2999999999999998,
                            Synopsis = "The Martian is a 2011 science fiction novel written by Andy Weir. It was his debut novel under his own name. It was originally self-published in 2011; Crown Publishing purchased the rights and re-released it in 2014.",
                            Title = "The Martian"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
